### ISSUE TITLE
How did you design the microSD footprint and align with PCB layout?

### ISSUE THREAD

**Issue by marcosscriven** [voltlog/emmc-wfbga153-microsd#3]
Hi

I'm trying to create a PCB that plugs into a microSD slot, as yours does (but for a different purpose).

I opened the project in KiCad and can see in the schematic you've laid out the pads, but I'm wondering how you made sure those pads were in the right spot compared to the PCB outline, which in this case is very important.

**Comment by voltlog** [comment]
Hi,
This is not an issue with the project.
